version: '2'

services:
  # backend code
  identity-reconcilation-backend:
    image: identity-reconcilation-backend
    build: ../server/
    command: python3 app.py 
    volumes:
      - ../server/:/usr/src/app/
    ports:
      - "5002:5002"
    networks:
      - identity_reconcil
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - PYTHONUNBUFFERED
    depends_on:
      postgres:
        condition: service_healthy

  # psql database
  postgres:
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PYTHONUNBUFFERED
    build: ../database
    networks:
      - identity_reconcil
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d customer_data'"]
      interval: 10s
      timeout: 2s
      retries: 3
    volumes:
      - ir_psql:/var/lib/postgresql/data

volumes:
  # psql database volume
  ir_psql:
    external: true

networks:
  identity_reconcil: 
    driver: bridge
